### ISSUE TITLE
Error 'File size is too big!' on empty form

### ISSUE THREAD

**Issue by felicjan** [joomdev/JD-Simple-Contact-Form#8] opened 2020-01-17 09:04 UTC
Hi, I get an error 'File size is too big!' already on empty form. The error does not disappear even if I choose an attachment.

Joomla! 3.9.14 Stable

**Comment by chetanmadaan** [comment] 2020-01-17 16:27
Can you provide a link to your website?

**Comment by actuallyakash** [comment] 2020-03-12 05:58
Not able to reproduce the issue.
Closing.  You can open it again anytime.

**Closed as completed by actuallyakash** 2020-03-12 05:58 UTC
